
/*
 * DCMOTOR_config.h
 *
 * Created: 5/24/2024 12:09:10 PM
 *  Author: NotFound
 */ 


#ifndef DCMOTOR_CONFIG_H_
#define DCMOTOR_CONFIG_H_

#define DCMOTOR_A_ENABLE_PORT		DIO_PORTD
#define DCMOTOR_A_ENABLE_PIN		DIO_PIN6

#define DCMOTOR_A_IN1_PORT			DIO_PORTD
#define DCMOTOR_A_IN1_PIN  			DIO_PIN3

#define DCMOTOR_A_IN2_PORT			DIO_PORTD
#define DCMOTOR_A_IN2_PIN  			DIO_PIN2

#define DCMOTOR_B_ENABLE_PORT		DIO_PORTD
#define DCMOTOR_B_ENABLE_PIN		DIO_PIN3

#define DCMOTOR_B_IN1_PORT			DIO_PORTD
#define DCMOTOR_B_IN1_PIN  			DIO_PIN3

#define DCMOTOR_B_IN2_PORT			DIO_PORTB
#define DCMOTOR_B_IN2_PIN  			DIO_PIN0


#endif /* DCMOTOR_CONFIG_H_ */