
/*
 * DCMOTOR_config.h
 *
 * Created: 5/24/2024 12:09:10 PM
 *  Author: NotFound
 */ 


#ifdef DCMOTOR_CONFIG_H_
#endif DCMOTOR_CONFIG_H_

#define DCMOTOR_A_ENABLE_PORT		DIO_PORTD
#define DCMOTOR_A_ENABLE_PIN		DIO_PIN4

#define DCMOTOR_A_IN1_PORT			DIO_PORTD
#define DCMOTOR_A_IN1_PIN  			DIO_PIN5

#define DCMOTOR_A_IN2_PORT			DIO_PORTD
#define DCMOTOR_A_IN2_PIN  			DIO_PIN6


#endif /* DCMOTOR_CONFIG_H_ */